name: Latest blog post workflow

on:
  schedule:
  - cron: '0 0 * * *' # Runs once a day at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "50"
          feed_list: "https://feeds.feedburner.com/blogwolkanca"
